name: shipnexusapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # Bloc for state management
  flutter_bloc: ^8.0.1
  # Functional programming things
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.3
  # Service locator
  get_it: ^8.0.2
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.6
  # Local cache
  shared_preferences: ^2.0.13
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.9
  injectable: ^2.5.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  http_interceptor: ^1.0.2
  intl_phone_field: ^3.2.0
  floor: ^1.5.0
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

  injectable_generator: ^2.4.1

flutter:

  assets:
      - assets/images/
      - assets/icons/
      - assets/fonts/

  uses-material-design: true

